## UpGrade 

### Assigment 3

Question 1 : Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [2]:
np.arange(2,50,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [3]:
np.arange(2,50,3).reshape(4,4)

array([[ 2,  5,  8, 11],
       [14, 17, 20, 23],
       [26, 29, 32, 35],
       [38, 41, 44, 47]])

Question 2: Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
arr1 = np.arange(5).reshape(5,1)
arr2 = np.arange(5).reshape(1,5)
print(arr1)
print()
print(arr2)
print(arr1 + arr2)

[[0]
 [1]
 [2]
 [3]
 [4]]

[[0 1 2 3 4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


Question 3 : Write a code snippet to find the dimensions of a ndarray and its size.

In [5]:
a = np.arange(5)
a
a.ndim
print(np.shape(a))
print(np.size(a))

(5,)
5


Question 4: How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [6]:
arr = np.array([1,2])
print(np.shape(arr))
print()
x=np.expand_dims(arr,axis=1)
print(x)
print()

(2,)

[[1]
 [2]]



In [7]:
b=np.arange(5)
print(b)

c=np.reshape(b,(5,1))
print(c)

print(b+c)

[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


Question 5 : Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [8]:
b=np.arange(5)


c=np.vstack(b)
d=np.hstack(b)

print(c)
print(d)

[[0]
 [1]
 [2]
 [3]
 [4]]
[0 1 2 3 4]


Question 6 : How to get unique items and counts of unique items?

In [9]:
arr = np.array([1,2,3,4,1,2,3,4,2,3,4,1,2,3])
print(np.unique(arr))
print()

[1 2 3 4]



In [10]:
np.unique(arr , return_counts = True)

(array([1, 2, 3, 4]), array([3, 4, 4, 3], dtype=int64))